require_relative '../lib/line'
require_relative '../lib/box'
require_relative 'spec_helper'

describe Line do
  before(:each) do
    @b = Box.new(20, 12, background: '.')
  end

  describe "horizontal line" do
    before(:each) do
      @l = Line.new(0,6,15,6)
      @b << @l
    end
    
    it "should do stuff" do
      @b.display.should == <<EOS
....................
....................
....................
....................
....................
....................
----------------....
....................
....................
....................
....................
....................
EOS
    end
    
  end

  describe "vertical line" do
    before(:each) do
      @l = Line.new(6, 0, 6, 8)
      @b << @l
    end
    
    it "should do stuff" do
      @b.display.should == <<EOS
......|.............
......|.............
......|.............
......|.............
......|.............
......|.............
......|.............
......|.............
......|.............
....................
....................
....................
EOS
    end
    
  end
  
  describe "angular line" do
    before(:each) do
      @l = Line.new(8, 0, 6, 8)
      @b << @l
    end
    
    it "display properly" do
      @b.display.should == <<EOS
........|...........
........|...........
........|...........
.......|............
.......|............
.......|............
.......|............
......|.............
......|.............
....................
....................
....................
EOS
    end
    
  end
  
  describe "angular line with end markings" do
    before(:each) do
      @l = Line.new(9, 8, 6, 0, ends_mark: '*')
      @b << @l
    end
    
    it "display properly" do
      @b.display.should == <<EOS
......*.............
......|.............
.......|............
.......|............
........|...........
........|...........
........|...........
.........|..........
.........*..........
....................
....................
....................
EOS
    end
  end
  
  describe "an arrow like line" do
    before(:each) do
      @l = Line.new(0, 6, 12, 5, start_mark: '|', end_mark: '>')
      @b << @l
    end
    
    it "display properly" do
      @b.display.should == <<EOS
....................
....................
....................
....................
....................
......------>.......
|-----..............
....................
....................
....................
....................
....................
EOS
    end
  end
  
end

